apiVersion: v2
name: ai-prototyping-tool
description: A Helm chart for AI Prototyping Tool
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/SamPlaysKeys/AI-Prototyping-Tool
sources:
  - https://github.com/SamPlaysKeys/AI-Prototyping-Tool
maintainers:
  - name: Sam Fleming
    email: info@samplayskeys.com
    url: https://github.com/SamPlaysKeys
  - ai
  - prototyping
  - machine-learning
  - lm-studio
icon: https://raw.githubusercontent.com/SamPlaysKeys/AI-Prototyping-Tool/main/docs/logo.png
dependencies: []
engine: gotpl
