version: '3.8'

services:
  ai-prototyping-web:
    build:
      context: ..
      dockerfile: web/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - ENV=development
    volumes:
      - ../output:/app/output
      - ../examples:/app/examples
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ai-prototyping-network

networks:
  ai-prototyping-network:
    driver: bridge

volumes:
  ai-prototyping-data:
    driver: local
